### ISSUE TITLE
Teach Arduino to detect number of connected drives

### ISSUE THREAD

**Issue by dstelljes** [morrislenny/umm-floppy-choir#11]
This may not be possible.

**Comment by joethe** [comment]
One thing to try might be to set the drive enable pins on the arduino to inputs temporarily (during startup or something) and also turn on their pull-ups, then read them all and (big maybe here, would need to see floppy circuit diagrams) whichever ones read as low are likely to be connected.

**Comment by dstelljes** [comment]
Further experimentation welcome here, but it doesn't seem easily possible. Leaving it as a constant for now.

**Comment by joethe** [comment]
The floppy's enable and step pins are pulled high (+5) by default, and upon startup of the Arduino we can probably enable pull-downs on the pins used to control the floppies and easily discern which pins are connected to drives.

**Comment by dstelljes** [comment]
Merged with 0ad0073.
